name: China
gdp: 43127100
health_resource_stockpile: 7462.0
sanitation_equipment_stockpile: 3710.0
human_welfare_resource: 1550.0
happiness_index: 0.9
procedure_resistance: 0.54
cleanliness_index: 0.735
disease_research_center: 0
vaccine_research_center: 0
vaccines_stock: 
  - name: ABC
    quantity: 20
    gdp_cost_per_step: 1000
    effectiveness: 0.4
  - name: ACB
    quantity: 30
    gdp_cost_per_step: 1000
    effectiveness: 0.22
  - name: BAC
    quantity: 10
    gdp_cost_per_step: 1000
    effectiveness: 0.95
  - name: BCA
    quantity: 12
    gdp_cost_per_step: 1000
    effectiveness: -0.2
  - name: CAB
    quantity: 23
    gdp_cost_per_step: 1000
    effectiveness: 0.5
  - name: CBA
    quantity: 10
    gdp_cost_per_step: 1000
    effectiveness: 0.1
loci:
  - name: Beijing
    B: 0.07
    C: 0.001
    E: 0.05
    A: 0.01
    Ds: 0.0004
    Di: 0.004
    Dr: 0.0001
    lat: 39.9042
    lon: 116.4074
    susceptible: 2154000
    infected: 10000
    recovered: 100
    dead: 0
    area: 307713
    quarantine_facilities: 2
    general_hospitals: 10
    vaccine_distribution_centers: 0
    airports:
      - name: Beijing Capital International Airport
        zone_tier: 1
        infection_rate : 0.002
        effect: 1.0
      - name: Beijing Daxing International Airport
        zone_tier: 2
        infection_rate : 0.002
        effect: 1.0
    ports:
      - name: Port of Tianjin
        infection_rate : 0.0004
        zone_tier: 1
        effect: 1.0
      - name: Port of Dalian
        zone_tier: 1
        infection_rate : 0.0004
        effect: 1.0
    economic_zones:
      - name: Zhongguancun
        zone_tier: 1
        effect: 1.0
      - name: Wangfujing
        zone_tier: 2
        effect: 1.0
      - name: Sanlitun
        zone_tier: 2
        effect: 1.0
    tourist_zones:
      - name: Great Wall of China
        zone_tier: 1
        effect: 1.0
      - name: Forbidden City
        zone_tier: 2
        effect: 1.0
      - name: Summer Palace
        zone_tier: 2
        effect: 1.0
  - name: Shanghai
    B: 0.05
    C: 0.003
    E: 0.02
    A: 0.04
    Ds: 0.0001
    Di: 0.005
    Dr: 0.0001
    lat: 31.2304
    lon: 121.4737
    susceptible: 242800
    infected: 10
    recovered: 100
    dead: 30
    area: 307713
    quarantine_facilities: 2
    general_hospitals: 10
    vaccine_distribution_centers: 0
    airports:
      - name: Shanghai Pudong International Airport
        zone_tier: 1
        infection_rate : 0.0004
        effect: 1.0
      - name: Shanghai Hongqiao International Airport
        zone_tier: 2
        infection_rate : 0.0004
        effect: 1.0
    ports:
      - name: Port of Shanghai
        zone_tier: 1
        infection_rate : 0.0002
        effect: 1.0
    economic_zones:
      - name: Lujiazui
        zone_tier: 1
        effect: 1.0
      - name: Xintiandi
        zone_tier: 2
        effect: 1.0
      - name: The Bund
        zone_tier: 2
        effect: 1.0
    tourist_zones:
      - name: The Bund
        zone_tier: 1
        effect: 1.0
      - name: Yu Garden
        zone_tier: 2
        effect: 1.0
      - name: Oriental Pearl Tower
        zone_tier: 2
        effect: 1.0
  - name: Guangdong
    B: 0.02
    C: 0.001
    E: 0.05
    A: 0.01
    Ds: 0.0004
    Di: 0.004
    Dr: 0.0001
    lat: 23.1136
    lon: 113.4221
    susceptible: 113460
    infected: 3000
    recovered: 420
    dead: 30
    area: 307713
    quarantine_facilities: 2
    general_hospitals: 10
    vaccine_distribution_centers: 0
    airports:
      - name: Guangzhou Baiyun International Airport
        zone_tier: 1
        infection_rate : 0.001
        effect: 1.0
      - name: Shenzhen Bao'an International Airport
        zone_tier: 2
        infection_rate : 0.0005
        effect: 1.0
    ports:
      - name: Port of Guangzhou
        zone_tier: 1
        infection_rate : 0.0001
        effect: 1.0
      - name: Port of Shenzhen
        zone_tier: 1
        infection_rate : 0.0002
        effect: 1.0
    economic_zones:
      - name: Shenzhen SEZ
        zone_tier: 1
        effect: 1.0
      - name: Guangzhou SEZ
        zone_tier: 2
        effect: 1.0
      - name: Zhuhai SEZ
        zone_tier: 2
        effect: 1.0
    tourist_zones:
      - name: Canton Tower
        zone_tier: 1
        effect: 1.0
      - name: Chimelong Paradise
        zone_tier: 2
        effect: 1.0
      - name: Window of the World
        zone_tier: 2
        effect: 1.0
  - name: Zhejiang
    B: 0.03
    C: 0.004
    E: 0.05
    A: 0.02
    Ds: 0.0004
    Di: 0.004
    Dr: 0.0001
    lat: 30.2638
    lon: 120.144
    susceptible: 645700
    infected: 5000
    recovered: 300
    dead: 30
    area: 307713
    quarantine_facilities: 2
    general_hospitals: 10
    vaccine_distribution_centers: 0
    airports:
      - name: Hangzhou Xiaoshan International Airport
        zone_tier: 1
        effect: 1.0
        infection_rate : 0.0009
      - name: Ningbo Lishe International Airport
        zone_tier: 2
        effect: 1.0
        infection_rate : 0.0008
    ports:
      - name: Port of Ningbo-Zhoushan
        zone_tier: 1
        infection_rate : 0.0001
        effect: 1.0
    economic_zones:
      - name: Hangzhou SEZ
        zone_tier: 1
        effect: 1.0
      - name: Ningbo SEZ
        zone_tier: 2
        effect: 1.0
      - name: Wenzhou SEZ
        zone_tier: 2
        effect: 1.0
    tourist_zones:
      - name: West Lake
        zone_tier: 1
        effect: 1.0
      - name: Xixi National Wetland Park
        zone_tier: 2
        effect: 1.0
      - name: Lingyin Temple
        zone_tier: 2
        effect: 1.0